### PR TITLE
Fixes #3 order by oldest first.

### LINKED ISSUE #3: Change Replay Upload Order
Currently the uploader uploads newest to oldest.  Switch to uploading oldest to newest

### PR DESCRIPTION
**Pull request by jgraniero52**
Changed orderByDescending to be order by ascending on the date, then order by descending on the time so that the oldest will be first. Fixes #3

### CODE REVIEW

**Comment by Zemill** [comment]
Hey, 
Thanks for this.  When looking at it, it appears that it also reverses the order of display.

I suppose I did not consider that.  I want the replays to upload in ASC mode, but display in DESC.

Thoughts?

**Comment by jgraniero52** [comment]
I can take a look and revise that!

**Comment by Zemill** [comment]
@M0shr00m or @jgraniero52 

The above solution works for flipping the order of uploaded replays to oldest to newest.  but it also reverses the order of the display, so users see the oldest replays at the top.  Not the best solution.

I took a quick look at the code, and I am not sure how to deal with it.  

https://github.com/Heroes-Profile/HeroesProfile.Uploader/blob/be165e48fbf0016eb9ffcd55dc3be45781939dca/Heroesprofile.Uploader.Windows/MainWindow.xaml#L36

The App.Manager.Files object is bound directly to the listBox.  I am not sure how to get it reversed in display only, but keeping all other data connections.

**Comment by jgraniero52** [comment]
Hey sorry things got hectic with the whole coronavirus thing and had to transition to setting up everything to be able to work from home. Now that I'm finally all set up I can get back to researching it!

**Comment by Zemill** [comment]
I found the correct solution to this issue and have it on my alternate branch for testing with the Prematch/PostMatch pages

**Pull request closed without merging**
